In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('data/train/train_final.csv', index_col=[0])
df_test = pd.read_csv('data/test/test_final.csv', index_col=[0])

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
print("Train size:", len(df_train))
print("Test size:", len(df_test))

Train size: 11430
Test size: 1590

In [5]:
df_test

,Team_ID,Match,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,std_FG_PCT,std_FG3_PCT,std_FT_PCT,std_OREB,std_DREB,std_AST,std_STL,std_BLK,std_TOV,std_PF,std_PTS,std_PLUS_MINUS,std_OFF_RATING,std_DEF_RATING,std_NET_RATING,std_AST_PCT,std_AST_TOV,std_AST_RATIO,std_OREB_PCT,std_DREB_PCT,std_REB_PCT,std_TM_TOV_PCT,std_EFG_PCT,std_TS_PCT,std_USG_PCT,std_PACE,std_POSS,std_PIE,Actual_PTS
0,1610612755,1610612738,240.000000,34.000000,87.000000,0.391000,5.000000,26.000000,0.1920,14.000000,23.000000,0.609000,6.000000,41.000000,47.0,18.000000,8.0,5.000000,16.000000,20.000000,87.000000,0.288152,0.122733,0.332689,1.035725,3.744086,2.335497,1.272078,0.820200,1.809068,1.887760,7.905119,4.214693,32.538196,22.684636,15.449095,0.118724,0.796291,13.151979,0.021532,0.114504,0.053823,10.277973,0.291060,0.261583,0.091407,10.797878,31.607249,0.087149,114
1,1610612755,1610612738,252.500000,36.000000,89.500000,0.402000,10.000000,33.000000,0.2835,18.500000,26.000000,0.701000,7.500000,44.000000,51.5,21.500000,7.0,4.500000,17.500000,20.500000,100.500000,0.213927,0.171777,0.399555,1.224970,4.305890,2.683866,1.136039,0.773341,1.821201,1.773036,9.458238,6.540492,21.068577,16.337239,16.851294,0.131735,1.525581,17.845272,0.027298,0.102745,0.053734,8.219469,0.216796,0.212766,0.085237,6.587618,29.464701,0.087011,109
2,1610612755,1610612738,248.333333,37.000000,86.333333,0.430667,9.666667,31.000000,0.3000,19.666667,27.666667,0.704000,8.333333,41.666667,50.0,21.333333,6.0,4.000000,16.333333,20.333333,103.333333,0.250624,0.250884,0.417257,1.201547,4.067812,2.218138,0.990428,0.740544,1.572456,1.748582,8.997272,6.361870,19.853605,14.955592,16.304284,0.130109,1.328923,21.060467,0.035921,0.119253,0.072989,9.458597,0.265800,0.260377,0.083631,5.012869,27.996147,0.078460,118
3,1610612755,1610612744,240.000000,41.000000,88.000000,0.466000,12.000000,37.000000,0.3240,19.000000,24.000000,0.792000,16.000000,33.000000,49.0,30.000000,11.0,5.000000,19.000000,19.000000,113.000000,0.175299,0.305356,0.484628,2.118700,4.498148,2.108185,1.100505,0.707107,2.514403,1.449138,8.393781,5.400617,21.142913,19.623345,12.719229,0.101756,0.989456,12.018430,0.056102,0.136537,0.090605,8.583731,0.254530,0.237073,0.101705,3.584542,21.988886,0.055575,117
4,1610612755,1610612760,240.000000,38.000000,81.000000,0.469000,11.000000,32.000000,0.3440,28.000000,39.000000,0.718000,12.000000,35.000000,47.0,28.000000,6.0,7.000000,17.000000,20.000000,115.000000,0.248588,0.323355,0.402310,1.500000,2.713137,3.059593,0.707107,0.833333,1.691482,1.394433,10.280780,11.889538,24.865628,11.576593,31.063957,0.159398,1.660405,13.493054,0.041814,0.088552,0.057250,6.734447,0.383123,0.365092,0.083274,1.726387,22.157266,0.056846,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585,1610612747,1610612741,240.000000,38.000000,82.000000,0.463000,8.000000,26.000000,0.3080,23.000000,34.000000,0.676000,13.000000,38.000000,51.0,21.000000,7.0,4.000000,17.000000,18.000000,107.000000,0.282346,0.197667,0.337371,1.424001,3.443996,2.538591,0.971825,1.013794,1.732051,1.130388,6.300353,9.367497,14.748559,9.733376,20.827232,0.094861,0.931450,11.305210,0.058142,0.090615,0.052953,16.305785,0.271949,0.209184,0.100941,5.468017,21.372360,0.054842,123
1586,1610612747,1610612764,240.000000,44.000000,91.000000,0.484000,11.000000,36.000000,0.3060,11.000000,18.000000,0.611000,8.000000,35.000000,43.0,24.000000,10.0,6.000000,22.000000,13.000000,110.000000,0.272636,0.242946,0.462910,1.164965,2.070197,1.885092,1.125992,0.707107,2.314550,1.414214,8.514693,14.292231,19.725794,17.285414,26.837221,0.168798,0.394489,12.129532,0.045302,0.067046,0.050071,12.625591,0.296120,0.254045,0.068113,2.698952,22.475383,0.117404,124
1587,1610612747,1610612757,240.000000,45.000000,93.000000,0.484000,7.000000,30.000000,0.2330,22.000000,29.000000,0.759000,8.000000,38.000000,46.0,23.000000,10.0,6.000000,15.000000,26.000000,119.000000,0.240444,0.353975,0.397726,1.166667,2.645751,3.741657,0.927961,1.118034,1.943651,2.061553,7.902180,8.660254,22.782449,17.722099,37.139717,0.134615,1.172966,13.021051,0.047336,0.134472,0.047702,6.587298,0.246911,0.242922,0.092782,7.233374,23.850809,0.062062,114
1588,1610612747,1610612757,240.000000,45.000000,89.500000,0.503500,7.500000,25.500000,0.3070,19.000000,27.000000,0.699500,8.500000,39.500000,48.0,21.500000,9.5,8.500000,17.500000,24.000000,116.500000,0.260900,0.402543,0.375328,1.113663,2.856720,3.278715,0.998503,1.591957,1.626479,1.807100,7.747235,13.905952,21.968930,16.163737,36.061055,0.150635,1.046696,12.735214,0.043939,0.104432,0.053173,7.028500,0.301345,0.270748,0.087853,4.801218,18.775522,0.073238,126
1589,1610612747,1610612757,240.000000,44.666667,90.666667,0.493333,10.000000,27.666667,0.3610,20.333333,26.666667,0.761333,9.333333,38.666667,48.0,22.666667,10.0,7.666667,16.000000,22.000000,119.666667,0.271406,0.376501,0.415697,1.314422,2.630963,3.115432,0.926247,1.433982,1.492568,1.743365,9.514507,10.036415,18.784324,15.632495,25.847541,0.146573,1.089651,12.850188,0.048371,0.091572,0.046551,6.790760,0.297863,0.283657,0.084353,4.891979,17.102620,0.079524,101

## Handle categorical features

In [6]:
# number of team
teams = np.unique(df_train['Team_ID'])
print(len(teams))
print(teams)

30
[1610612737 1610612738 1610612739 1610612740 1610612741 1610612742
 1610612743 1610612744 1610612745 1610612746 1610612747 1610612748
 1610612749 1610612750 1610612751 1610612752 1610612753 1610612754
 1610612755 1610612756 1610612757 1610612758 1610612759 1610612760
 1610612761 1610612762 1610612763 1610612764 1610612765 1610612766]

In [7]:
df_train.groupby(['Team_ID', 'Match']).size()

Team_ID     Match
1610612737  1610612738    17
            1610612739    17
            1610612740     9
            1610612741    17
            1610612742     9
                          ..
1610612766  1610612761    17
            1610612762     9
            1610612763     9
            1610612764    19
            1610612765    16
Length: 870, dtype: int64

In [8]:
# convert team_id from int to string

df_train['Team_ID'] = df_train['Team_ID'].astype(str)
df_train['Match'] = df_train['Match'].astype(str)
df_test['Team_ID'] = df_test['Team_ID'].astype(str)
df_test['Match'] = df_test['Match'].astype(str)

In [9]:
# Feature hashing scheme

from sklearn.feature_extraction import FeatureHasher

In [10]:
fh = FeatureHasher(n_features=6, input_type='string')
hashed_teamid = fh.fit_transform(df_train['Team_ID'])
hashed_teamid = hashed_teamid.toarray()
df_x_train = pd.DataFrame(hashed_teamid, columns=['t0', 't1', 't2', 't3', 't4', 't5'])

In [11]:
df_x_train

        t0   t1   t2   t3   t4   t5
0      1.0 -4.0  2.0  1.0  0.0  0.0
1      1.0 -4.0  2.0  1.0  0.0  0.0
2      1.0 -4.0  2.0  1.0  0.0  0.0
3      1.0 -4.0  2.0  1.0  0.0  0.0
4      1.0 -4.0  2.0  1.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...
11425  0.0 -4.0  1.0  1.0  0.0  0.0
11426  0.0 -4.0  1.0  1.0  0.0  0.0
11427  0.0 -4.0  1.0  1.0  0.0  0.0
11428  0.0 -4.0  1.0  1.0  0.0  0.0
11429  0.0 -4.0  1.0  1.0  0.0  0.0

[11430 rows x 6 columns]

In [12]:
hashed_match = fh.transform(df_train['Match'])
hashed_match = hashed_match.toarray()

In [13]:
df_x_train = pd.concat([df_x_train, pd.DataFrame(hashed_match, columns=['m0', 'm1', 'm2', 'm3', 'm4', 'm5'])], axis=1)

In [14]:
df_x_train

        t0   t1   t2   t3   t4   t5   m0   m1   m2   m3   m4   m5
0      1.0 -4.0  2.0  1.0  0.0  0.0  2.0 -4.0  3.0  1.0  0.0  0.0
1      1.0 -4.0  2.0  1.0  0.0  0.0  2.0 -4.0  3.0  1.0  0.0  0.0
2      1.0 -4.0  2.0  1.0  0.0  0.0  2.0 -4.0  3.0  1.0  0.0  0.0
3      1.0 -4.0  2.0  1.0  0.0  0.0  2.0 -4.0  3.0  1.0  0.0  0.0
4      1.0 -4.0  2.0  1.0  0.0  0.0  2.0 -4.0  3.0  1.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
11425  0.0 -4.0  1.0  1.0  0.0  0.0  1.0 -4.0  3.0  0.0  0.0  0.0
11426  0.0 -4.0  1.0  1.0  0.0  0.0  1.0 -4.0  3.0  0.0  0.0  0.0
11427  0.0 -4.0  1.0  1.0  0.0  0.0  1.0 -4.0  3.0  0.0  0.0  0.0
11428  0.0 -4.0  1.0  1.0  0.0  0.0  1.0 -4.0  3.0  0.0  0.0  0.0
11429  0.0 -4.0  1.0  1.0  0.0  0.0  1.0 -4.0  3.0  0.0  0.0  0.0

[11430 rows x 12 columns]

In [15]:
hashed_teamid = fh.transform(df_test['Team_ID'])
hashed_teamid = hashed_teamid.toarray()

hashed_match = fh.transform(df_test['Match'])
hashed_match = hashed_match.toarray()

In [16]:
df_x_test = pd.DataFrame(hashed_teamid, columns=['t0', 't1', 't2', 't3', 't4', 't5'])
df_x_test = pd.concat([df_x_test, pd.DataFrame(hashed_match, columns=['m0', 'm1', 'm2', 'm3', 'm4', 'm5'])], axis=1)

## Normalizing the data

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
# select the features we would like to scale (all except Actual_PTS)

train_features = df_train.iloc[:, 2:-1]

In [19]:
train_features

,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,std_FG_PCT,std_FG3_PCT,std_FT_PCT,std_OREB,std_DREB,std_AST,std_STL,std_BLK,std_TOV,std_PF,std_PTS,std_PLUS_MINUS,std_OFF_RATING,std_DEF_RATING,std_NET_RATING,std_AST_PCT,std_AST_TOV,std_AST_RATIO,std_OREB_PCT,std_DREB_PCT,std_REB_PCT,std_TM_TOV_PCT,std_EFG_PCT,std_TS_PCT,std_USG_PCT,std_PACE,std_POSS,std_PIE
0,240.000000,34.000000,71.000000,0.479000,7.000000,17.000000,0.412000,22.000000,32.000000,0.688000,10.000000,34.000000,44.000000,17.000000,4.000000,18.000000,20.000000,13.000000,97.000000,0.298756,0.231455,0.399851,2.070197,3.284161,1.752549,0.462910,2.507133,1.302470,1.726888,7.559289,8.631338,36.079889,31.543609,61.199520,0.111258,0.525043,6.953879,0.087658,0.093972,0.078216,15.844958,0.334662,0.315412,0.077091,3.814738,23.212912,0.143290
1,240.000000,36.000000,80.500000,0.450500,7.500000,21.000000,0.366000,18.000000,24.500000,0.756000,11.500000,36.500000,48.000000,19.000000,4.000000,11.500000,14.500000,13.000000,97.500000,0.304173,0.223740,0.429660,1.509440,2.884837,1.685938,0.568929,1.569794,1.188719,1.413697,6.789351,10.120121,31.246778,30.503588,57.667115,0.112673,0.368458,9.236909,0.085591,0.102870,0.066856,16.224769,0.330092,0.323446,0.086761,2.661548,21.273697,0.138331
2,240.000000,35.666667,80.000000,0.448000,8.666667,22.000000,0.396667,15.666667,22.666667,0.697000,10.000000,35.666667,45.666667,19.000000,4.666667,9.666667,14.666667,15.333333,95.666667,0.306591,0.236362,0.420996,1.449347,2.723688,2.010066,0.561860,1.580557,1.251948,1.486795,7.622229,9.126446,23.484771,24.109769,43.877715,0.120340,1.158509,11.231024,0.080974,0.112225,0.062255,15.756718,0.320516,0.289391,0.079519,3.527400,19.765840,0.121254
3,240.000000,37.000000,82.000000,0.452500,9.250000,22.250000,0.417000,13.750000,19.750000,0.704500,11.250000,36.000000,47.250000,20.750000,4.750000,7.750000,14.000000,15.750000,97.000000,0.264146,0.238036,0.428729,1.538940,2.504469,1.908441,0.610378,1.301145,1.220459,1.546819,7.225204,8.591004,19.397985,20.832911,36.830522,0.108736,1.136143,10.744242,0.078981,0.105963,0.064056,13.418877,0.280695,0.246386,0.073697,2.852133,18.146216,0.102246
4,240.000000,37.800000,84.400000,0.449200,8.200000,21.000000,0.383600,13.400000,18.600000,0.735000,12.400000,36.000000,48.400000,21.600000,5.200000,6.800000,13.400000,16.000000,97.200000,0.241765,0.219277,0.438103,1.647486,2.489569,1.954371,0.710841,1.138506,1.127553,1.520298,6.318238,7.868986,17.266225,17.617459,30.828082,0.108640,1.066274,11.431114,0.076899,0.104613,0.066090,12.197188,0.256963,0.224367,0.064960,2.675907,16.851395,0.096420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,241.666667,41.733333,86.400000,0.483133,12.133333,31.533333,0.381000,17.133333,22.066667,0.771867,10.333333,35.333333,45.666667,29.133333,10.466667,6.533333,15.133333,21.800000,112.733333,0.246881,0.281598,0.419802,1.236797,2.825650,2.940069,1.136701,0.991987,1.553833,1.513769,7.642255,10.553173,18.568237,18.994761,30.306274,0.148439,1.582894,16.307772,0.069622,0.096655,0.067543,9.649315,0.270751,0.247205,0.083639,5.039214,21.990647,0.123933
11426,241.562500,41.875000,86.562500,0.483812,12.000000,31.500000,0.377375,17.062500,21.812500,0.779187,10.500000,35.062500,45.562500,29.625000,10.687500,6.625000,14.937500,21.375000,112.812500,0.249550,0.274104,0.423775,1.269378,2.791817,2.990168,1.183643,0.961521,1.545107,1.462949,7.706208,10.681424,18.746799,20.624259,32.373266,0.157622,1.563132,16.218586,0.073810,0.109946,0.075074,9.996839,0.272307,0.250350,0.083487,5.148858,22.020036,0.121398
11427,241.470588,41.764706,86.176471,0.484765,12.235294,31.823529,0.380588,16.647059,21.352941,0.775353,10.411765,34.588235,45.000000,29.705882,10.588235,6.588235,14.882353,21.000000,112.411765,0.255760,0.279601,0.420214,1.269373,2.729478,2.979203,1.190588,0.935963,1.508804,1.458919,7.584355,10.256876,18.480748,19.882498,31.168382,0.158103,1.563021,16.374104,0.077477,0.109250,0.076624,10.341372,0.277660,0.256227,0.081094,5.006165,22.120483,0.118317
11428,241.388889,41.888889,85.833333,0.488389,12.500000,31.888889,0.388056,16.500000,21.055556,0.780889,10.222222,35.111111,45.333333,29.444444,10.444444,6.444444,15.444444,20.888889,112.777778,0.256507,0.279457,0.423705,1.285909,2.737250,2.968186,1.181821,0.922810,1.556450,1.457303,7.785538,9.941300,18.599698,19.638172,29.951000,0.166456,1.507961,17.197633,0.077620,0.111278,0.078279,10.675332,0.278973,0.259571,0.082274,4.913388,22.612305,0.118194
11429,241.315789,41.473684,85.578947,0.484789,12.473684,31.578947,0.391947,16.315789,20.894737,0.777789,10.157895,34.894737,45.052632,29.000000,10.421053,6.368421,15.210526,20.894737,111.736842,0.257854,0.279219,0.425809,1.255446,2.752776,2.915385,1.200493,0.912477,1.546333,1.440097,7.788520,9.612842,18.980781,19.852666,29.077553,0.163715,1.488572,17.776952,0.078113,0.111103,0.077311,10.812902,0.281236,0.262396,0.082354,4.900835,22.602000,0.116406

In [20]:
# MinMaxScaler
scaler = MinMaxScaler()
train_features = scaler.fit_transform(train_features.values)
test_features = scaler.transform(df_test.iloc[:, 2:-1])

In [21]:
train_features.shape

(11430, 47)

In [22]:
train_features

array([[0.        , 0.39393939, 0.12244898, ..., 0.00205325, 0.52672256,
        0.04879667],
       [0.        , 0.45454545, 0.31632653, ..., 0.00129082, 0.47077362,
        0.04679107],
       [0.        , 0.44444444, 0.30612245, ..., 0.00186328, 0.42726991,
        0.03988373],
       ...,
       [0.01960784, 0.62923351, 0.43217287, ..., 0.00284097, 0.49520451,
        0.03869605],
       [0.01851852, 0.63299663, 0.42517007, ..., 0.00277963, 0.50939424,
        0.03864618],
       [0.01754386, 0.62041467, 0.41997852, ..., 0.00277133, 0.50909693,
        0.03792293]])

In [23]:
# concatenate categorical data with other features 

x_train = []

for i in range(len(df_train)):
    row = np.concatenate((df_x_train.values[i], train_features[i]))
    x_train.append(row)
    
x_test = []

for i in range(len(df_test)):
    row = np.concatenate((df_x_test.values[i], test_features[i]))
    x_test.append(row)

In [24]:
x_train = np.array(x_train)
x_test = np.array(x_test)

In [25]:
x_train

array([[ 1.00000000e+00, -4.00000000e+00,  2.00000000e+00, ...,
         2.05325478e-03,  5.26722560e-01,  4.87966684e-02],
       [ 1.00000000e+00, -4.00000000e+00,  2.00000000e+00, ...,
         1.29082382e-03,  4.70773623e-01,  4.67910747e-02],
       [ 1.00000000e+00, -4.00000000e+00,  2.00000000e+00, ...,
         1.86328167e-03,  4.27269913e-01,  3.98837292e-02],
       ...,
       [ 0.00000000e+00, -4.00000000e+00,  1.00000000e+00, ...,
         2.84096592e-03,  4.95204508e-01,  3.86960506e-02],
       [ 0.00000000e+00, -4.00000000e+00,  1.00000000e+00, ...,
         2.77962683e-03,  5.09394243e-01,  3.86461801e-02],
       [ 0.00000000e+00, -4.00000000e+00,  1.00000000e+00, ...,
         2.77132730e-03,  5.09096932e-01,  3.79229271e-02]])

In [26]:
x_test

array([[ 2.00000000e+00, -4.00000000e+00,  3.00000000e+00, ...,
         6.67015375e-03,  7.68910404e-01,  2.60895425e-02],
       [ 2.00000000e+00, -4.00000000e+00,  3.00000000e+00, ...,
         3.88654235e-03,  7.07095019e-01,  2.60334051e-02],
       [ 2.00000000e+00, -4.00000000e+00,  3.00000000e+00, ...,
         2.84539807e-03,  6.64725299e-01,  2.25748885e-02],
       ...,
       [ 0.00000000e+00, -4.00000000e+00,  3.00000000e+00, ...,
         4.31348401e-03,  5.45126753e-01,  1.59424782e-02],
       [ 0.00000000e+00, -4.00000000e+00,  3.00000000e+00, ...,
         2.70546549e-03,  3.98697923e-01,  2.04628258e-02],
       [ 0.00000000e+00, -4.00000000e+00,  3.00000000e+00, ...,
         2.76547176e-03,  3.50432468e-01,  2.30053861e-02]])

In [27]:
x_train = np.reshape(x_train, (x_train.shape[0], 1, x_train.shape[1]))
x_test = np.reshape(x_test, (x_test.shape[0], 1, x_test.shape[1]))

In [29]:
print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)

x_train shape: (11430, 1, 59)
x_test shape: (1590, 1, 59)

In [30]:
# prediction y is the Actual_PTS

y_train = df_train.iloc[:, -1]
y_test = df_test.iloc[:, -1]

## Build the model

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.optimizers import RMSprop

In [34]:
model = Sequential()
model.add(SimpleRNN(units=32, input_shape=(1,59), activation="relu"))
model.add(Dense(8, activation="relu")) 
model.add(Dense(1))

In [35]:
model.compile(optimizer=RMSprop(), loss='mae')

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
simple_rnn_1 (SimpleRNN)     (None, 32)                2944
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 264
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9
=================================================================
Total params: 3,217
Trainable params: 3,217
Non-trainable params: 0
_________________________________________________________________

## Train the model

In [38]:
history = model.fit(x_train, y_train, batch_size=16, epochs=10,
         validation_data=(x_test, y_test))

Train on 11430 samples, validate on 1590 samples
Epoch 1/10
11430/11430 [==============================] - 2s 135us/sample - loss: 9.7052 - val_loss: 10.6745
Epoch 2/10
11430/11430 [==============================] - 1s 110us/sample - loss: 9.6744 - val_loss: 10.7918
Epoch 3/10
11430/11430 [==============================] - 1s 109us/sample - loss: 9.6576 - val_loss: 10.3191
Epoch 4/10
11430/11430 [==============================] - 1s 114us/sample - loss: 9.6336 - val_loss: 10.3815
Epoch 5/10
11430/11430 [==============================] - 1s 121us/sample - loss: 9.6353 - val_loss: 10.2552
Epoch 6/10
11430/11430 [==============================] - 1s 120us/sample - loss: 9.6093 - val_loss: 10.2477
Epoch 7/10
11430/11430 [==============================] - 1s 110us/sample - loss: 9.6063 - val_loss: 10.2001
Epoch 8/10
11430/11430 [==============================] - 1s 109us/sample - loss: 9.5867 - val_loss: 10.4099
Epoch 9/10
11430/11430 [==============================] - 1s 122us/sample - loss: 9.5787 - val_loss: 10.2011
Epoch 10/10
11430/11430 [==============================] - 2s 153us/sample - loss: 9.5654 - val_loss: 10.3839

In [40]:
pred = model.predict(x_test)

In [41]:
# actual points and predicted
df = pd.DataFrame({'Actual': y_test, 'Predicted': pred.flatten()})
df

      Actual   Predicted
0        114   98.998482
1        109  106.471626
2        118  105.895561
3        117  113.237984
4        108  113.448822
...      ...         ...
1585     123  107.108665
1586     124  108.460701
1587     114  112.635414
1588     126  111.127235
1589     101  112.176201

[1590 rows x 2 columns]

In [42]:
# creating intervals, allowing prediction to be no more or less than 5 points

df["low"] = df["Predicted"] -5
df["high"] = df["Predicted"] +5

In [43]:
df

      Actual   Predicted         low        high
0        114   98.998482   93.998482  103.998482
1        109  106.471626  101.471626  111.471626
2        118  105.895561  100.895561  110.895561
3        117  113.237984  108.237984  118.237984
4        108  113.448822  108.448822  118.448822
...      ...         ...         ...         ...
1585     123  107.108665  102.108665  112.108665
1586     124  108.460701  103.460701  113.460701
1587     114  112.635414  107.635414  117.635414
1588     126  111.127235  106.127235  116.127235
1589     101  112.176201  107.176201  117.176201

[1590 rows x 4 columns]

In [302]:
# displaying the ga

df[(df["Actual"]>df["low"]) & (df["Actual"]<df["high"])]

      Actual   Predicted         low        high
1        109  106.329163  101.329163  111.329163
3        117  113.318993  108.318993  118.318993
10       109  111.224915  106.224915  116.224915
12       116  112.329308  107.329308  117.329308
16       103  104.640182   99.640182  109.640182
...      ...         ...         ...         ...
1576     105  108.728012  103.728012  113.728012
1579      99  103.393799   98.393799  108.393799
1581     107  107.935654  102.935654  112.935654
1584     109  107.914680  102.914680  112.914680
1587     114  112.803596  107.803596  117.803596

[498 rows x 4 columns]